name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 10
        uses: actions/setup-java@v1
        with:
          java-version: 10
      - uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: 'Start to build with maven'
      - uses: actions/cache@v1
        id: hello
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Compress generated file
        id: compress_generated_files
        run: zip -r SiroLibrary-${{ steps.hello.outputs.time }} $HOME/work/SiroLibrary/SiroLibrary/target
      - name: test
        run: pwd      
      - name: Print file list
        run: ls -a
