name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 10
        uses: actions/setup-java@v1
        with:
          java-version: 10
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}     
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: print home path
        run: echo $HOME
