name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven release
      uses: qcastel/github-actions-maven-release@v1.0.3
      with:
        # The git user name for commiting the release
        git-release-bot-name: "Release-Bot"
        # The git user email for commiting the release
        git-release-bot-email: "siro.shun8@gmail.com"
        gpg-enabled: "false"
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
        access-token: ${{ secrets.GITHUB_TOKEN }}
