name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 10
        uses: actions/setup-java@v1
        with:
          java-version: 10
      - uses: actions/hello-world-javascript-action@master
        id: hello
        with:
          who-to-greet: 'Start to build with maven'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Compress generated file
        id: compress_generated_files
        run: zip -r ${GITHUB_REPOSITORY##*/} target/
      - name: Send generated files to Discord (S)
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_S }}
        with:
          args: ${GITHUB_REPOSITORY##*/}.zip
      - name: Send generated files to Discord (O)
        uses: sinshutu/upload-to-discord@master
        if: github.ref == refs/heads/master
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_O }}
        with:
          args: ${GITHUB_REPOSITORY##*/}.zip
